trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - azure-pipeline.yaml
      - terraform/*

jobs:
  - job: BuildAndPublish
    displayName: Build and Publish Site Content
    steps:
      - task: NodeTool@0
        displayName: Install NodeJS
        inputs:
          versionSpec: 12.x
      - task: Npm@1
        displayName: Install NPM packages
        inputs:
          command: install
      - task: Bash@3
        displayName: Build Gatsby site
        inputs:
          targetType: inline
          script: |
            node_modules/.bin/gatsby build
      - task: AWSShellScript@1
        displayName: "Upload build to site bucket"
        inputs:
          awsCredentials: 'AWS Production'
          regionName: 'us-east-1'
          scriptType: 'inline'
          inlineScript: 'aws s3 sync --delete public/ s3://josh.feiermanfamily.com/'